# SPDX-FileCopyrightText: 2015 - 2024 Rime community
#
# SPDX-License-Identifier: GPL-3.0-or-later

# add alipay QR code for sponsor
custom: https://raw.githubusercontent.com/osfans/trime/develop/osfans_alipay.png
